_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 23
                - 55
            "4": 3.11.4
            "5": 0.18.1
            "6": 4.44.2
            "8":
                - 5
            "12": 0.18.1
            "13": darwin-arm64
